export enum ColorsBikes {
  WHITE = 'WHITE',
  BLACK = 'BLACK',
  SILVER = 'SILVER',
  GRAY = 'GRAY',
  RED = 'RED',
  BROWN = 'BROWN',
  YELLOW = 'YELLOW',
  OLIVE = 'OLIVE',
  LIME = 'LIME',
  GREEN = 'GREEN',
  AQUA = 'AQUA',
  TEAL = 'TEAL',
  BLUE = 'BLUE',
  NAVY = 'NAVY',
  PINK = 'PINK',
  VIOLET = 'VIOLET',
}

export enum BikesTypes {
  ROADS_BIKES = 'ROADS_BIKES',
  MOUNTAIN_BIKES = 'MOUNTAIN_BIKES',
  HYBRID_BIKES = 'HYBRID_BIKES',
  ELECTRIC_BIKES = 'ELECTRIC_BIKES',
  TOURING_BIKES = 'TOURING_BIKES',
  FOLDING_BIKES = 'FOLDING_BIKES',
  KIDS_BIKES = 'KIDS_BIKES',
}
